Dgii.Challenge.Frontend.Web/Models/ErrorViewModel.cs
namespace Dgii.Challenge.Frontend.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Dgii.Challenge.Frontend.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Dgii.Challenge.Frontend.Web.Models;

namespace Dgii.Challenge.Frontend.Web.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Dgii.Challenge.Frontend.Web/Controllers/TaxPayerController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Dgii.Challenge.Frontend.Lib.Services;
using Dgii.Challenge.Frontend.Lib.Services.Interfaces;

namespace Dgii.Challenge.Frontend.Web.Controllers;

public class TaxPayerController : Controller
{
    private readonly ITaxPayerServices taxPayerServices;
    private readonly IVoucherServices voucherServices;
    private readonly ILogger<TaxPayerController> _logger;

    public TaxPayerController(ILogger<TaxPayerController> logger)
    {
        _logger = logger;
        taxPayerServices = new TaxPayerServices();
        voucherServices = new VoucherServices();
    }

    public IActionResult Index()
    {
        return View(taxPayerServices.Get());
    }

    [Route("TaxPayer/Vouchers/{rnc}")]
    public IActionResult Vouchers(string rnc = "")
    {
        if (string.IsNullOrWhiteSpace(rnc))
        {
            return NotFound();
        }
        return View(voucherServices.Get(rnc.Trim()));
    }
}

Dgii.Challenge.Frontend.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <!--
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    -->
</div>

Dgii.Challenge.Frontend.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DGII Challenge</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Dgii.Challenge.Frontend.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dgii Challenge</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TaxPayer" asp-action="Index">Contribuyentes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DGII Challenge by Erick Choque Navia - <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Dgii.Challenge.Frontend.Web/Views/TaxPayer/Index.cshtml
@model IEnumerable<Dgii.Challenge.Frontend.Lib.Models.TaxPayer>

@{
    ViewData["Title"] = "Index";
}

<h2>Lista de Contribuyentes</h2>
<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Rnc)</th>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th>@Html.DisplayNameFor(model => model.Type)</th>
            <th>@Html.DisplayNameFor(model => model.State)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.Rnc</td>
            <td>@item.Name</td>
            <td>@item.Type</td>
            <td>@item.State</td>
            <td>
                <a asp-action="Vouchers" asp-route-id="@item.Rnc">Comprobantes</a>
            </td>
        </tr>
        }
    </tbody>
</table>

Dgii.Challenge.Frontend.Web/Views/TaxPayer/Vouchers.cshtml
@model IEnumerable<Dgii.Challenge.Frontend.Lib.Models.Voucher>

@{
    ViewData["Title"] = "Index";
    double totalAmount = 0;
    double totalItbis18 = 0;
}

<h2>Lista de Contribuyentes</h2>
<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Rnc)</th>
            <th>@Html.DisplayNameFor(model => model.Encf)</th>
            <th>@Html.DisplayNameFor(model => model.Amount)</th>
            <th>@Html.DisplayNameFor(model => model.Itbis18)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            totalAmount += item.Amount;
            totalItbis18 += item.Itbis18;
        <tr>
            <td>@item.Rnc</td>
            <td>@item.Encf</td>
            <td>@item.Amount</td>
            <td>@item.Itbis18</td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th colspan="2">Total</th>
            <th>@totalAmount</th>
            <th>@totalItbis18</th>
        </tr>
    </tfoot>
</table>